### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [ToastinYou/NoReticle#11]
is it possible to have the marksman/sniper reticle only on when aiming in FIRST PERSON view as opposed to when someone is just ADS in THIRD PERSON view?

**Comment by ToastinYou** [comment]
> is it possible to have the marksman/sniper reticle only on when aiming in FIRST PERSON view as opposed to when someone is just ADS in THIRD PERSON view?

this should be fixed in version 2.3.0.
